### ISSUE TITLE
Rendering preview does not work on version 1.2

### ISSUE THREAD

**Issue by Juke34** [royfrancis/shiny-doorsign#1]
compared to version 1.1.2
<img width="1319" alt="Capture d’écran 2023-11-08 à 12 39 10" src="https://github.com/royfrancis/shiny-doorsign/assets/6769395/29e4baa5-a9a5-4c11-b68b-5419166fdb84">

cheers

**Comment by royfrancis** [comment]
Did you click on "Update"?

**Comment by Juke34** [comment]
🫢 my bad. Thx
